### ISSUE TITLE
MVP slashing

### ISSUE THREAD

**Issue by JakeHartnell** [osmosis-labs/mesh-security#112]
Related to #11, this ticket is focused on _what to do when a slash occurs_ (as opposed to detecting a slash).

Assuming a slash occurs and is valid, how do we:
- Slash balances in the vault for delegators to the offending validator
- Handle slashing locally staked native tokens
- Update consumers so that cross-staked amounts are correct

In the future there will be a full fledged slasher contract for verification (likely many different slashing implementations). For purposes of this initial MVP, we do not actually need to build out the slasher contract or detection, rather implementing the slash itself and propagation.

**Comment by maurolacy** [comment]
Closed by #126.
