### ISSUE TITLE
Improve rewards withdrawal process

### ISSUE THREAD

**Issue by maurolacy** [osmosis-labs/mesh-security#123]
The current rewards withdrawal process would break if a validator was slashed or fell out of the validator set.

See

https://github.com/osmosis-labs/mesh-security/blob/8e520dfdd9bc716c2723e2b349bef47baf8446cd/contracts/consumer/virtual-staking/src/contract.rs#L78-L97

And this comment

https://github.com/osmosis-labs/mesh-security/blob/8e520dfdd9bc716c2723e2b349bef47baf8446cd/contracts/consumer/virtual-staking/src/contract.rs#L138-L150

Fixing this requiring keeping track of the active validator set on the Consumer (i.e. on the `virtual-staking` contract).

This is similar to the way the valset is being kept up-to-date in Tgrade. You can take a look at [`tgrade-valset`](https://github.com/confio/poe-contracts/tree/main/contracts/tgrade-valset) for inspiration / ideas.

**Comment by uint** [comment]
I think this was dealt with in #137. @maurolacy Do we close this, or is there more to do?

**Comment by maurolacy** [comment]
There's more to do, but will be dealt with during full valset state implementation (#118). Closing.
