### ISSUE TITLE
Implement Remote Staking contract (no rewards)

### ISSUE THREAD

**Issue by ethanfrey** [osmosis-labs/mesh-security#13]
* It takes leins from the Vault and sends IBC messages
* User can specify which validator
* User can initiate (partial or full) unbonding - triggers IBC message and local claim window
* When local claim completed, can release (full or partial) lein on the vault
~~* Currently a user must have all tokens staked on one remote validator, and cannot split (Fix for V1 - #12)~~

There is a follow up issue to handle rewards: https://github.com/osmosis-labs/mesh-security/issues/43

**Comment by ethanfrey** [comment]
For first demo version, let's do this:

* Bond message from the vault (leave a TODO where it should send IBC message, but don't implement that)
* Unstake message from owner
  * Move from staking to "unbonding" window. (record expiration)
  * Leave TODO for sending IBC message
* Claim/Withdraw/??? message (pick a better name) from owner
  * Once unstake record is "mature" (expiration has passed), then we allow them to release lien on vault contract

**Comment by ethanfrey** [comment]
The next step can make a "distribute rewards" message callable by anyone. It takes tokens (the remote IBC token, can be specified in init, different than native staking)

This should be a cw2222 style implementation for lazy withdrawl. We need some changes, as we track rewards for each validator separately, thus have a dynamic set of  buckets for withdraw.

We need to specify (validator, user) pair to withdraw rewards. Maybe we can query the validator given the user, so we only expose user (`info.sender`) in the `WithdrawRewards` message. And look up the validator from contract-local storage before calling into the cw2222 code.

**Comment by hashedone** [comment]
To be done:
- [ ] Implement basic bare-bone contract for external staking
- [ ] Add the possibility to choose the validator when staking externally for the first time
- [ ] Test for external staking/unstaking
- [ ] Rewards distribution (cw2222)
- [ ] Tests for rewards distribution
