### ISSUE TITLE
Native slashing SDK / routing mechanism

### ISSUE THREAD

**Issue by maurolacy** [osmosis-labs/mesh-security#174]
(This or an equivalent issue must be created on the `mesh-security-sdk` repo. Creating here for visibility / reference).

A `x/meshsecurity` module is required on the Provider, so that slashing events can be forwarded to the contracts for processing.

The native slashing implementation at the contracts level (#129) is done.

**Comment by maurolacy** [comment]
This would probably need to be a different project / repository. Something like `mesh-security-provider-sdk` or so.

Not sure, but perhaps some common library can be built, including functionality that can be used on both SDKs.

**Comment by likesToEatFish** [comment]
In BeforeValidatorSlashed there is not enough context to use such as InfractionTime, power, SlashAmount for [out_msg](https://github.com/osmosis-labs/mesh-security-sdk/blob/main/x/meshsecurity/contract/out_message.go#L18). So there are two solutions:
- Fix sdk section [BeforeValidatorSlashed](https://github.com/cosmos/cosmos-sdk/blob/v0.47.5/x/staking/keeper/slash.go#L128)
- Get from BeginBlock something like this [beginblock](https://github.com/likesToEatFish/mesh-security-sdk/blob/a2767c8cf5a3bfb570442109a01bfadd53c5cd15/x/meshsecurity/abci.go#L20)

Or is there a better idea?
