### ISSUE TITLE
Refine epochs and delegation distributions

### ISSUE THREAD

**Issue by alpe** [osmosis-labs/mesh-security#24]
Common regular operations for virtual staking are:
 - claim rewards
 - adopt to price changes
 - redistribute delegations

In an epoch model, a time based trigger starts the execution. This brings a "fair" and predicable process but may put a lot of load on single blocks. It would be good to discuss alternatives.

Other external events:
- max cap modified
- new un-/ delegation
- price update
- slashing hook
-...?

**Comment by ethanfrey** [comment]
I think we are moving forward quite a bit with epochs in the virtual staking module and using endblock callbacks for eg max cap modified (or any other event that needs a quicker update).

> This brings a "fair" and predicable process but may put a lot of load on single blocks. It would be good to discuss alternatives.

Adding a gas limit to those callbacks is good (and planned) do you have any other alternatives?

**Comment by ethanfrey** [comment]
This should be one epoch per provider chain. And yes, it will iterate over all validators and withdraw all rewards and send ibc packets, as well as restaking.

I would keep the different provider epochs with some offset between them, but I wouldn't break each provider into multiple epochs. The outstanding optimization is to send the rewards in batches, which would be a lot less resource intensive.

Please see #77 for the follow up issue to address this point
