### ISSUE TITLE
Implement local staking proxy

### ISSUE THREAD

**Issue by maurolacy** [osmosis-labs/mesh-security#34]
Complementary to the local staking contract.

- Receive stake from the local staking module.
- Unstake to the local staking module.

Also includes #8 for the full workflow of local proxy management

**Comment by ethanfrey** [comment]
I reviewed the state of the proxy and it looks pretty complete.

I guess this is about addressing TODO and FIXME and covering with some tests?

**Comment by ethanfrey** [comment]
Closed by #41
