### ISSUE TITLE
How does the virtual staking contract receives an update on max cap modified

### ISSUE THREAD

**Issue by alpe** [osmosis-labs/mesh-security#36]
Changes to the max-cap limit by the consumer gov process need to be communicated to the contract.
This can be done via a callback on the gov update or by a query from the contract in an epoch. What is the preferred solution?

I can see some arguments for a callback as the chain gov may set the limit to `0` . This may require some instant actions to undelegate and provide a good UX on the provider side.

**Comment by ethanfrey** [comment]
We discussed this a bit more here: https://github.com/osmosis-labs/mesh-security-sdk/pull/14#discussion_r1206377919

I thought more about this and I think the threat model should be malicious external code / ibc packets / user-controlled contracts.

Governance priviledged contracts should be considered as safe as sdk modules (voted in by gov in an upgrade). Therefore I would not consider that the virtual staking contract and the virtual staking module should be mutually distrustful.

Given that, I would just use a `SudoMsg::Rebalance{}` call to the virtual staking contract every time the max cap changes. It is normally called once per epoch to adjust weights to the current remote staking. But it also has to query the max cap to determine how to adjust this. Simply calling this when max cap changes (even to 0) would trigger all proper bonding/unbonding calls.

I would be less trusting of the other contracts, but let's consider these two a package.

**Comment by ethanfrey** [comment]
If this makes sense to you, I will update the docs and happy for the corresponding PR in https://github.com/osmosis-labs/mesh-security-sdk
