### ISSUE TITLE
Use batch distribute_rewards for cross-chain distribution efficiency

### ISSUE THREAD

**Issue by ethanfrey** [osmosis-labs/mesh-security#77]
The converter contract has distribute_reward, which we use now, which is called once per each validator getting rewards and then issues an ibc packet. This is N contract calls and N ibc packets every epoch.

There is also a distribute_rewards method that takes a batch of validators (all N?). This means only one contract call (saving N-1 * 60k gas). We could also use this to make one ibc packet with all distribution info.

This requires much more complex withdraw logic in the virtual-staking contract, and first we need to be able to cover that with unit tests. This in turn is blocked on some sylvia updates, and likely some cw-multi-test updates.

But when we have those dependencies ready, this would be a nice optimization to tackle.

**Comment by maurolacy** [comment]
The function to optimise is this

https://github.com/osmosis-labs/mesh-security/blob/8e520dfdd9bc716c2723e2b349bef47baf8446cd/contracts/consumer/converter/src/contract.rs#L276-L300

**Comment by uint** [comment]
@maurolacy Do we want to keep events in the current form (N events emitted for N validators being rewarded)? I guess this makes it easier for some hypothetical future indexer to index these txes?

**Comment by maurolacy** [comment]
I think so, yes. Let's keep the events in their current form.
