### ISSUE TITLE
Explain ValueRange more

### ISSUE THREAD

**Issue by ethanfrey** [osmosis-labs/mesh-security#83]
Especially why this is correct and under what conditions.

Basically: it works when all operations are commutative (add and subtract) within a range, as they error on a boundary condition. If we can guarantee all outstanding transactions will in no case hit a boundary condition, then they are commutative and can be freely applied in any order. If it may be possible to hit these (min or max) boundaries, then it is unsafe to perform them concurrently.

ValueRange tracks the possible range when resolving all outstanding transactions as either commit or rollback, and can be checked against boundary conditions before adding a new tx to the set of pending transactions.

**Comment by maurolacy** [comment]
Closed by #97.
