### ISSUE TITLE
Allow depositing vesting tokens in the vault

### ISSUE THREAD

**Issue by ethanfrey** [osmosis-labs/mesh-security#90]
Builds on #89 but making the vault even closer to native staking.

**Situation**: I have 1000 vesting $OSMO, which I could stake normally on one validator. It is currently not staked at all.

**Problem**: I wish to use these tokens for mesh-security so I can also stake on Juno and Akash, however, I am unable to deposit these tokens in the vault.

There is no clear design how to change this as this would involve deep changes in the bank / auth module to change how vesting works. This issue serves to track any design work or ideas on how to make this possible.

**Comment by neitdung** [comment]
@vuong177, 

As per our last discussion, I believe our current solution has some issues that necessitate a redesign. Please share your thoughts on this matter:

### Original Solution

**Flow:**
- Deposit: The tokens will be delegated to the x/meshsecurity-provider module, similar to how the [[x/staking delegate calls the bankeeper](https://github.com/cosmos/cosmos-sdk/blob/main/x/staking/keeper/delegation.go#L742)](https://github.com/cosmos/cosmos-sdk/blob/main/x/staking/keeper/delegation.go#L742). After this, the module will deposit the tokens to the vault as usual.
- Withdraw : x/meshsecurity-provider module withdraws token from contract and sends back token to user. We need to make sure undelegation amounts are still tracked for both vesting and vested coins.

**Problems:**
- The need to separate normal users and vesting users at the vault contract increases the complexity of bonding and unbonding.
- This solution affects other PRs, such as zero max-cap, slashing, etc.

### New Solution

- Users can only **bond** and **unbond** through the provider module.
- For **bonding**, the module will use `DelegateCoinsFromAccountToModule` to move user coins to the vault contract via `wasmtypes.MsgExecuteContract`.
- For **unbonding**, the module will call `unbond` to the contract and receive an `unbond response`. The provider module will then unmarshall the information about the delegator and unbond amount and use `UndelegateCoinsFromAccountToModule` to return the coins to the user.

**Benefits:**
- Does not affect other PRs.
- Requires minimal code changes.
- Avoids creating new `Map` storage in the contract.
