### ISSUE TITLE
Locked state of contracts return consistent response

### ISSUE THREAD

**Issue by Anmol1696** [osmosis-labs/mesh-security#93]
## Overview
When contracts are in `locked` state, they should return that information in a consistent way for all contracts.

## Currently
`external-staking` contract returns an error on undelegate msg:
```
smart query error (ignored): rpc error: code = Unknown desc = Value is already write locked: query wasm contract failed: unknown request
```

While it on `delegate` it returns query response of `locked: {}`. Which is more consistent.

## Proposal
If contract is is locked state, it should not return an error, but a response of `locked: {}`.

**Comment by maurolacy** [comment]
Thanks for reporting this. Wi fix it asap.

**Comment by maurolacy** [comment]
I was taking a look at the relevant methods (external-staking `receive_virtual_stake` and `unstake`) and I see consisten behaviour. Perhaps I'm looking at the wrong functions? Can you post an example / test in which this happens?

**Comment by maurolacy** [comment]
Will work on making the *queries* return `Locked` for locked items instead of errors. That will standardise all the queries behaviours.
